spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/aula-teste
    password: admin
    username: postgres
    driverClassName: org.postgresql.Driver
